### ISSUE TITLE
Provide a Flatpak as software package for Linux

### ISSUE THREAD

**Issue by vladimiroff** [trustcrypto/OnlyKey-App#105]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

Doing this will enable usage on other than debian or debian-based distributions.

**Comment by KNO56** [comment]
Would really appreciate if someone would make this happen! I'm having issues with running on my Arch install; both the package in the AUR, attempting to install the .deb with debtap, and running the Windows version in Wine fail for me.

**Comment by onlykey** [comment]
@KNO56 There is also a CLI app, I know we have some users on Arch using that - https://github.com/trustcrypto/python-onlykey

**Comment by vladimiroff** [comment]
@KNO56 the package in AUR stopped working at some point due to fontconfig updates. I've pushed an update to 5.2.0 which should work fine now.

Creating the AUR package is tedious, though. It actually downloads the .deb file built *obviously* for debian-based distributions, unpacks it and packs it back for Arch. That seems strange at first, why bother getting the .deb package and then unpack it, instead of just calling `npm build` and package it?

The reason is that the release command for linux actually only works under Debian (or Ubuntu or any other derivative) and uses the assumption that this is going to be used on such distribution by directly [calling dpkg-deb](https://github.com/trustcrypto/OnlyKey-App/blob/v5.2.0/tasks/release_linux.js#L74). Creating release task just for arch is would need pretty much copy-pasting [release_linux.js](https://github.com/trustcrypto/OnlyKey-App/blob/v5.2.0/tasks/release_linux.js) and change it slightly. Probably introducing flags for the release command for arch would work, too.

However, that means we've just covered two major distributions. What about the rest? This made me to request a [Flatpak](https://flatpak.org/) package which would benefit users of all distributions. On a second thought [AppImage](https://appimage.org/) would work, too.

**Comment by onlykey** [comment]
@vladimiroff We did publish a snapcraft package, I would like to do a Flatpak as well but just finding the time to do this. Any assistance here would be great, here is the snapcraft.yaml, it simply extracts the .deb and links to the command and the desktop file.

```
name: onlykey-app
version: '5.2.0'
summary: Setup and configure OnlyKey
description: |
 Use this app to setup and configure OnlyKey for password management and 2-factor authentication.

grade: stable
confinement: devmode

parts:
  onlykey-app:
    plugin: dump
    source: OnlyKey_5.2.0_amd64.deb
    source-type: deb
    after:
      - nwjs-support
      - desktop-gtk3
    stage-packages:
      - gir1.2-gnomekeyring-1.0
      - libasound2
      - libgconf-2-4
      - libgl1-mesa-glx
      - libglu1-mesa
      - libgnome-keyring0
      - libcap2
      - libgcrypt20
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxtst6
      - libxss1

apps:
  onlykey-app:
    command: bin/desktop-launch  $SNAP/opt/OnlyKey/nw
    desktop: usr/share/applications/OnlyKey.desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

 ```

Documentation has been updated to include snap instructions - https://docs.crp.to/linux.html
